nama = input("Masukkan nama lengkap: ")
kelas = input("Masukkan kelas")
npm = input("Masukkan npm")
jurusan = input("Masukan jurusan")
tl = int(input("Masukkan tanggal lahir:"))
umur = 2018 - tl
alamat = input("Masukan alamat lengkap")
print("Halo! ", nama)
print("Kelasmu di ", kelas )
print("NPMmu adalah ", npm)
print("Jurusanmu adalah", jurusan)
print("Umur kamu", umur)
#serahhhh sheeeebbbbb nih kutambahin hoho
print("Alamat kamu", alamat)
print("Selesai :)")